apiVersion: v1
kind: Service
metadata:
  name: devforge-order-svc-8c40f5-svc
  labels:
    app.kubernetes.io/name: order-svc-8c40f5
    app.kubernetes.io/instance: order-svc-8c40f5
    app.kubernetes.io/part-of: devforge
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: order-svc-8c40f5
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
